export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --highlight-line \
  --info=inline-right \
  --ansi \
  --layout=reverse \
  --border=none \
  --color=bg+:#394b70 \
  --color=bg:#000000 \
  --color=border:#ffffff \
  --color=fg:#c0caf5 \
  --color=gutter:#000000 \
  --color=header:#ff9e64 \
  --color=hl+:#2ac3de \
  --color=hl:#2ac3de \
  --color=info:#545c7e \
  --color=marker:#ff007c \
  --color=pointer:#ff007c \
  --color=prompt:#2ac3de \
  --color=query:#c0caf5:regular \
  --color=scrollbar:#ffffff \
  --color=separator:#ff9e64 \
  --color=spinner:#ff007c \
"
