core:
  - all:
      - changed-files:
          - any-glob-to-any-file: "lua/milkoutside/**"
          - all-globs-to-all-files:
              - "!lua/milkoutside/groups/**"
              - "!lua/milkoutside/colors/**"
              - "!lua/milkoutside/extra/**"

extras:
  - changed-files:
      - any-glob-to-any-file: "lua/milkoutside/extra/**"

groups:
  - changed-files:
      - any-glob-to-any-file: "lua/milkoutside/groups/**"

base:
  - changed-files:
      - any-glob-to-any-file:
          - "lua/milkoutside/groups/base.lua"
          - "lua/milkoutside/groups/kinds.lua"
          - "lua/milkoutside/groups/treesitter.lua"
          - "lua/milkoutside/groups/semantic_tokens.lua"

colors:
  - changed-files:
      - any-glob-to-any-file: "lua/milkoutside/colors/**"
