# Theme: milkoutside
# By: Folke Lemaitre

theme[main_bg]="#040607"
theme[main_fg]="#e8e8e8"

# Title color for boxes
theme[title]="#e8e8e8"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#ffad00"

# Selected item in processes box
theme[selected_bg]="#394b70"
theme[selected_fg]="#63c3dd"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#63c3dd"